### ISSUE TITLE
How do I use this from scratch?

### ISSUE THREAD

**Issue by TNBU0** [jsln/pps-gen-gpio#6]
I have previously setup NTP/PTP/etc on a Beagle bone black before; but I am struggling incorporating this at the moment. 
Could you provide some more verbose steps for configuring a PPS from a blank BBB? Thank you kindly.

**Comment by jsln** [comment]
Hi, did you manage to compile a kernel for the BBB? I guess that would be the first step. As soon as you compile a kernel, using DT, for the BBB, then it would be easy to add this driver later on.

Sorry, I am quite busy this week, but I will have more time from next week onwards, let me know how it goes.

**Comment by TNBU0** [comment]
Do I need to include this when I compile the image? 

Currently trying this again since I have a beagle bone black on hand;
I am getting compilation issues about "linux/init.h";
I am not super versed in building kernel modules or the such; am i correct that even on beagle's this codebase is not plug and play?

**Comment by jsln** [comment]
Hi, to be honest I am not sure if this code compiles with latest kernels, I would propose to get familiar with building generic kernel modules for the beaglebone, e.g. have a look at the link below (and accompanying book). Then you would need to see if you can use this module in your kernel. Sorry for not being more detailed in my answer.

http://exploringbeaglebone.com/chapter16/

**Comment by TNBU0** [comment]
Thanks for the hints.

By chance, do you know of a download for beagle image that I could prove this module / code on?

**Comment by jsln** [comment]
Sorry, I don´t know of any download images.

**Comment by TNBU0** [comment]
I was successful following dereks guide to understanding and loading some of LKM stuff. Thank you.

Your gpio pps gen module is not working for me, the dmesg tells me that i have more than one pps gen loaded in the device tree.
I attempted to make my own dts file, the one you have is giving me issues around missing dependancies "
#include "am33xx.dtsi"
#include "am335x-bone-common.dtsi"
#include "am335x-boneblack-common.dtsi""

Were you using package "https://github.com/beagleboard/bb.org-overlays" for building your dtbo file?

Thank you.

**Comment by jsln** [comment]
> Were you using package "https://github.com/beagleboard/bb.org-overlays" for building your dtbo file?

I was not using that package.

**Comment by TNBU0** [comment]
I have not gotten this to work yet.
Did you cross compile / build the kernel yourself? Did you build this into the kernel?

I would like to monitor the beagle's kpps on a scope and use it to sync other devices; so any insight would be appreciated in this endeavor!

**Comment by TNBU0** [comment]
Loaded module taints kernel... Still struggling. If any more verbose documentation for instantiating this on a clean beagle, that would be helpful.

**Comment by jsln** [comment]
> Loaded module taints kernel... Still struggling. If any more verbose documentation for instantiating this on a clean beagle, that would be helpful.

It's been some time since I don´t work with the BBB, but I hope to have some time the next few days to try again and use a more recent kernel so that I can update the README. What version are you using? I will probably try longterm 6.1.

**Comment by TNBU0** [comment]
I have tried on Beagle's supplied image of Debian 10.3 w/ Kernel 4.19 ([afaik](https://beagleboard.org/latest-images)).
Kernel 4.19.94-ti-r73 was tried with one of the monthly snapshots from [here](https://forum.beagleboard.org/t/debian-10-x-buster-monthly-snapshots/31203).
I also found someone "port forwarded" this module to 5.4 but i could not get that to work either.
https://github.com/damon-kwok/pps-gen-gpio

Best of luck and many thanks @jsln

**Comment by TNBU0** [comment]
![image](https://user-images.githubusercontent.com/89268071/219103860-55924ed9-9832-4f76-983b-adaaec807e0e.png)

I tried this again an hour ago, nothing being generated. Would that be a device tree issue?

**Comment by TNBU0** [comment]
I checked "show-pins"
![image](https://user-images.githubusercontent.com/89268071/219106538-fa83c7d3-c200-4249-a597-c4661f9c4a38.png)
and i see the pin is in the right mode but it does not have anything after where the image cuts off. no mention of a (pinmux_pps_gen_pinx) or the like so i believe this is a device tree issue. But I cannot confirm yet.

**Comment by TNBU0** [comment]
Device tree issues resolved. Rebuilt the dts file to accomdate whatever has changed for the bbb platform. Generating 3.3v pps out of gpio of beagle.

**Comment by jsln** [comment]
> Device tree issues resolved. Rebuilt the dts file to accomdate whatever has changed for the bbb platform. Generating 3.3v pps out of gpio of beagle.

fantastic, @TNBU0 !

I am still setting up my beaglebone black with linux 6.1, hopefully in the next few days I should be trying the device tree stuff, it would be great if you could share your update!

**Comment by TNBU0** [comment]
I retyped and uploaded several different versions the dts. I believe the end result was something was a "_" instead of a "-". I still cannot get it working on a device that also accepts a pps input from gnss/gps/glonass/external reference. But that is a different error/issue for another time.

The DTC did not give any errors but i was not getting the full configuration of the pin (show-pins is a blessing).
